-- FOR EACH ARTICLE VISIBLE IN GIVEN TIME PERIOD, DETERMINE WHETHER A ARTICLE CATEGORY WAS DETECTED BY THE JUICER
CREATE OR REPLACE TABLE ANALYTICS_DB.ARTICLE_CATEGORY_DETECTED_BOOLEAN_{week_or_month!i}LY AS

    -- GET ALL DISTINCT ARTICLES VISIBLE IN THE GIVEN TIME PERIOD
    With distinct_articles_tbl AS
            (SELECT DISTINCT A.ID
              FROM ARTICLES_DB.ARTICLES P

               -- INNER JOIN TO ONLY GET VISIBLE ARTICLES
            INNER JOIN ARTICLES_DB.VISIBLE_ARTICLES_DAILY V
                          ON A.ID = V.ARTICLE_ID
            WHERE TRUE
                AND to_date(V.DAY_DATE) >= {start_date}
                AND to_date(V.DAY_DATE) <= {end_date}
            )

    -- NEED TO SELECT DISTINCT BECAUSE ARTICLE_ID || ENTITY_TYPE CAN OCCUR MULTIPLE TIMES IN EACH TABLE
    SELECT DISTINCT
        A.ID,

        -- CHECK WHETHER AT LEAST ONE OF THE ONTOLOGY TABLES CONTAINS AN ENTRY FOR THE GIVEN ARTICLE
        CASE WHEN T.ARTICLE_ID IS NULL AND S.ARTICLE_ID IS NULL AND A.ARTICLE_ID IS NULL THEN 0 ELSE 1 END AS ARTICLE_CATEGORY_DETECTED

    FROM distinct_articles_tbl P


    -- CHECK IF ARTICLE CATEGORY WAS DETECTED VIA ARTICLE TITLE
    LEFT JOIN HIVE_DB_ONTOLOGY_ENTITIZED.ARTICLES_TITLE T
    ON A.ID = T.ARTICLE_ID
    AND T.ENTITY_TYPE = 'ARTICLE_CATEGORY'


    -- CHECK IF ARTICLE CATEGORY WAS DETECTED VIA ARTICLE TAGS
    LEFT JOIN HIVE_DB_ONTOLOGY_ENTITIZED.ARTICLES_TAG A
    ON A.ID = A.ARTICLE_ID
    AND A.ENTITY_TYPE = 'ARTICLE_CATEGORY'

;
